language: scala
os:
  - linux
services:
  - mysql
  - cassandra
  - elasticsearch
jdk:
  - oraclejdk8
scala:
   - 2.11.8
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
script:
  - mysql -uroot -e "show databases;"
  - cd cmsfs
  - sbt ++$TRAVIS_SCALA_VERSION test
notifications:
  email:
    recipients:
      - 191631513@qq.com
    on_success: always
    on_failure: always