language: scala
services:
  - mysql
  - cassandra
  - elasticsearch
jdk:
  - oraclejdk8
scala:
   - 2.11.8
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
script:
   - cd cmsfs; sbt test
notifications:
  email:
    - 191631513@qq.com
