PUT http://10.65.103.15:49673/v1/node/3 HTTP/1.1
content-type: application/json

{
    "ip":"abc1111c",
    "hostname":"aaa",
    "port":22,
    "tags":[
        "a"
    ],
    "status": true,
    "label":"fdf打发打发"
}

###

DELETE  http://10.65.103.15:49673/v1/node/2 HTTP/1.1

###

POST http://10.65.103.15:9000/v1/node HTTP/1.1
content-type: application/json

{
    "ip":"1abcc",
    "hostname":"aaa",
    "port":22,
    "tags":[
        "a"
    ],
    "status": true,
    "label":"fdf打发打发"
}

###

GET http://10.65.103.15:49673/v1/node/2 HTTP/1.1