FROM cmsfs/oraclejdk8

ARG SVC_NAME

ADD cmsfs/${SVC_NAME}/impl/target/universal/stage /opt/cmsfs/
ADD logback.xml /opt/logback.xml
ADD register.sh /usr/local/bin/register.sh

EXPOSE 9000

RUN ln -s /opt/cmsfs/bin/${SVC_NAME}-impl /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh", "-Dplay.crypto.secret=abcdefghijk", "-Dlogger.file=/opt/logback.xml"]

CMD ["sh", "-c", "register.sh"]