FROM cmsfs/oraclejdk8

ARG SVC_NAME

LABEL traefik.backend=cmsfs-$SVC_NAME
LABEL traefik.frontend.rule=Host:$SVC_NAME.cmsfs.org
LABEL traefik.port=9000

ADD cmsfs/${SVC_NAME}/impl/target/universal/stage /opt/cmsfs
ADD logback.xml /opt/logback.xml

EXPOSE 9000

ENTRYPOINT ["/opt/cmsfs/bin/cmsfs-service"]

CMD [-Dplay.crypto.secret=abcdefghijk, -Dlogger.file=/opt/logback.xml]
