FROM cmsfs/oraclejdk8

ARG SVC_NAME
ARG BOOTSTRAP_NAME

ADD register.py register.py
ADD entrypoint.sh /usr/local/bin/entrypoint.sh
ADD logback.xml /opt/logback.xml

ENV SERVICE_NAME ${SVC_NAME}

EXPOSE 9000

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]

CMD ["-Dplay.crypto.secret=abcdefghijk", "-Dlogger.file=/opt/logback.xml"]

RUN ln -s /opt/cmsfs/bin/${BOOTSTRAP_NAME} /usr/local/bin/app.sh
ADD cmsfs/${SVC_NAME} /opt/cmsfs