FROM cmsfs/oraclejdk8

ARG SVC_NAME
ARG SVC_PORT

ADD register.py register.py
ADD entrypoint.sh /usr/local/bin/entrypoint.sh
ADD logback.xml /opt/logback.xml

ENV SERVICE_NAME ${SVC_NAME}
ENV SERVICE_PORT ${SVC_PORT}
ENV BOOTSTRAP_FILE ${SVC_NAME}-impl

EXPOSE ${SERVICE_PORT}

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]

CMD ["-Dplay.crypto.secret=abcdefghijk", "-Dlogger.file=/opt/logback.xml"]

ADD ${SVC_NAME}-impl-1.0-SNAPSHOT /opt/cmsfs