version: "2.1"

services:
  proxy:
    container_name: cmsfs_proxy
    image: traefik
    restart: always
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG --entryPoints='Name:http Address::9000' --defaultEntryPoints='http'
    expose:
      - "9000"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  config:
    container_name: cmsfs_config
    build:
      context: ./
      dockerfile: Dockerfile-lagom
      args:
        SVC_NAME: config
        SVC_HOST_NAME: config
    image: cmsfs/config
    depends_on:
      - proxy
      - db
    links:
      - db:db.cmsfs.org
      
  monitor:
    container_name: cmsfs_monitor
    build:
      context: ./
      dockerfile: Dockerfile-lagom
      args:
        SVC_NAME: monitor
        SVC_HOST_NAME: monitor
    image: cmsfs/monitor
    depends_on:
      - config
    links:
      - db:db.cmsfs.org
      - proxy:config.cmsfs.org
      - proxy:ssh.collect.cmsfs.org
      
  format:
    build:
      context: ./
      dockerfile: Dockerfile-lagom
      args:
        SVC_NAME: format
        SVC_HOST_NAME: format
    image: cmsfs/format
    depends_on:
      - config
    links:
      - proxy:config.cmsfs.org
      
  collect-ssh:
    build:
      context: ./
      dockerfile: Dockerfile-lagom
      args:
        SVC_NAME: collect-ssh
        SVC_HOST_NAME: ssh.collect
    image: cmsfs/collect-ssh
    volumes:
      - /root/.ssh/id_rsa:/root/.ssh/id_rsa
    depends_on:
      - monitor
    links:
      - proxy:monitor.cmsfs.org

  db:
    container_name: cmsfs_db
    image: mysql
    expose:
      - "3306"
    labels:
      - "traefik.backend=cmsfs-db"
      - "traefik.frontend.rule=Host:db.cmsfs.org"
      - "traefik.port=3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456aA+
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "ss -lt | grep mysql"]
      interval: 3s
      timeout: 2s
      retries: 10

  db_data:
    container_name: cmsfs_db_data
    image: mysql
    volumes:
      - ./db/:/opt/
    links:
      - db:db.cmsfs.org
    command: sh -c "/bin/bash /opt/load.sh"
    depends_on:
      db:
        condition: service_healthy

  # grafana:
  #   container_name: cmsfs_grafana
  #   image: grafana/grafana
  #   ports: 
  #     - "3000:3000"
  #   environment: 
  #     - GF_SECURITY_ADMIN_PASSWORD=123456aA+ 

  # elasticsearch:
  #   container_name: cmsfs_elasticsearch
  #   image: elasticsearch
  #   ports: 
  #     - "9300:9300"